{
<<<<<<< HEAD:jogos/Encaixe/offline.js
	"version": 1499368572,
=======
	"version": 1499101632,
>>>>>>> 72747e13cda39fa3b4ae37eff9b9af392b65b62f:Encaixe/offline.js
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/imagempassaro-sheet0.png",
		"images/imagempassaro-sheet1.png",
		"images/imagempassaro-sheet2.png",
		"images/sensorfim-sheet0.png",
		"images/fillegito-sheet0.png",
		"images/brilho-sheet0.png",
		"images/artbgegito-sheet0.png",
		"images/chao-sheet0.png",
		"images/titulo-sheet0.png",
		"images/menu_1_topo-sheet0.png",
		"images/menu_2_fixo-sheet0.png",
		"images/menu_3_topo-sheet0.png",
		"images/logotapioca-sheet0.png",
		"images/logobebe-sheet0.png",
		"images/logobebe-sheet1.png",
		"images/fimegito-sheet0.png",
		"images/iconecrianca-sheet0.png",
		"images/clique-sheet0.png",
		"images/loadimage-sheet0.png",
		"images/artbgleao-sheet0.png",
		"images/fillleao-sheet0.png",
		"images/imagemleao-sheet0.png",
		"images/touchesq-sheet0.png",
		"images/touchdir-sheet0.png",
		"images/fimleao-sheet0.png",
		"images/artbgcavalo-sheet0.png",
		"images/imagemcavalo-sheet0.png",
		"images/imagemcavalo-sheet1.png",
		"images/imagemcavalo-sheet2.png",
		"images/imagemcavalo-sheet3.png",
		"images/imagemcavalo-sheet4.png",
		"images/fimcavalo-sheet0.png",
		"images/fillcavalo-sheet0.png",
		"images/setaesq-sheet0.png",
		"images/setadir-sheet0.png",
		"images/iconesom-sheet0.png",
		"images/iconesom-sheet1.png",
<<<<<<< HEAD:jogos/Encaixe/offline.js
		"media/efeito_tapa.m4a",
		"media/efeito_tapa.ogg",
=======
		"images/artbgjapao-sheet0.png",
		"images/fimmenino-sheet0.png",
		"images/imagemjapao-sheet0.png",
		"images/filljapao-sheet0.png",
		"images/artfloatjapao-sheet0.png",
		"media/efeito_tapa.m4a",
		"media/efeito_tapa.ogg",
		"media/efeito_crianca.m4a",
		"media/efeito_crianca.ogg",
>>>>>>> 72747e13cda39fa3b4ae37eff9b9af392b65b62f:Encaixe/offline.js
		"media/efeito_leao.m4a",
		"media/efeito_leao.ogg",
		"media/efeito_cavalo.m4a",
		"media/efeito_cavalo.ogg",
		"media/efeito_passaro.m4a",
		"media/efeito_passaro.ogg",
		"media/bg fase 1.ogg",
		"media/bg fase 2.ogg",
		"media/bg fase 4.ogg",
<<<<<<< HEAD:jogos/Encaixe/offline.js
=======
		"media/bg fase 6.ogg",
>>>>>>> 72747e13cda39fa3b4ae37eff9b9af392b65b62f:Encaixe/offline.js
		"media/bg_calmo.m4a",
		"media/bg_calmo.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}