{
	"version": 1498798124,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/imagempassaro-sheet0.png",
		"images/imagempassaro-sheet1.png",
		"images/imagempassaro-sheet2.png",
		"images/sensorfim-sheet0.png",
		"images/fillegito-sheet0.png",
		"images/brilho-sheet0.png",
		"images/artbgegito-sheet0.png",
		"images/chao-sheet0.png",
		"images/titulo-sheet0.png",
		"images/menu_1_topo-sheet0.png",
		"images/menu_2_fixo-sheet0.png",
		"images/menu_3_topo-sheet0.png",
		"images/logotapioca-sheet0.png",
		"images/logobebe-sheet0.png",
		"images/fimegito-sheet0.png",
		"images/iconecrianca-sheet0.png",
		"images/clique-sheet0.png",
		"images/clique-sheet1.png",
		"images/clique-sheet2.png",
		"images/loadimage-sheet0.png",
		"images/artbgleao-sheet0.png",
		"images/fillleao-sheet0.png",
		"images/imagemleao-sheet0.png",
		"images/touchesq-sheet0.png",
		"images/touchdir-sheet0.png",
		"images/fimleao-sheet0.png",
		"images/artbgcavalo-sheet0.png",
		"images/imagemcavalo-sheet0.png",
		"images/imagemcavalo-sheet1.png",
		"images/imagemcavalo-sheet2.png",
		"images/imagemcavalo-sheet3.png",
		"images/imagemcavalo-sheet4.png",
		"images/fimcavalo-sheet0.png",
		"images/fillcavalo-sheet0.png",
		"images/setaesq-sheet0.png",
		"images/setadir-sheet0.png",
		"images/iconesom-sheet0.png",
		"images/iconesom-sheet1.png",
		"images/artbgbarco-sheet0.png",
		"images/artbgcachorro-sheet0.png",
		"images/artbgjapao-sheet0.png",
		"images/fimmenino-sheet0.png",
		"images/fimcachorro-sheet0.png",
		"images/fimbarco-sheet0.png",
		"images/imagembarco-sheet0.png",
		"images/imagembarco-sheet1.png",
		"images/imagembarco-sheet2.png",
		"images/fillbarco-sheet0.png",
		"images/imagemcachorro-sheet0.png",
		"images/imagemcachorro-sheet1.png",
		"images/fillcachorro-sheet0.png",
		"images/artfloatbarco-sheet0.png",
		"images/imagemjapao-sheet0.png",
		"images/filljapao-sheet0.png",
		"images/artfloatjapao-sheet0.png",
		"media/efeito_tapa.m4a",
		"media/efeito_tapa.ogg",
		"media/efeito_crianca.m4a",
		"media/efeito_crianca.ogg",
		"media/bg_calmo.m4a",
		"media/bg_calmo.ogg",
		"media/mysterious_calm.ogg",
		"media/lion roar loud.m4a",
		"media/lion roar loud.ogg",
		"media/calm town.ogg",
		"media/horse whinny.m4a",
		"media/horse whinny.ogg",
		"media/bg japao.ogg",
		"media/arrr.m4a",
		"media/arrr.ogg",
		"media/barco bg.ogg",
		"media/160093__jorickhoofd__dog-bark-2.m4a",
		"media/160093__jorickhoofd__dog-bark-2.ogg",
		"media/woods.m4a",
		"media/woods.ogg",
		"media/34207__cajo__birds-01.m4a",
		"media/34207__cajo__birds-01.ogg",
		"media/a lucid dream.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}