{
	"version": 1501193644,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/safearea-sheet0.png",
		"images/ititulo-sheet0.png",
		"images/islidebar-sheet0.png",
		"images/iareadireita-sheet0.png",
		"images/stop1-sheet0.png",
		"images/iitem-sheet0.png",
		"images/iitem-sheet1.png",
		"images/idropzone-sheet0.png",
		"images/ishowmonster-sheet0.png",
		"images/sfshowmonstername.png",
		"images/ifeverbar.png",
		"images/ifeverbar_top-sheet0.png",
		"images/ifever-sheet0.png",
		"images/sfmonsterinfo.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}