{
	"version": 1504409680,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bplay-sheet0.png",
		"images/bshop-sheet0.png",
		"images/ideath_head-sheet0.png",
		"images/ideath_head-sheet1.png",
		"images/ileveldisplay-sheet0.png",
		"images/iloadingbar.png",
		"images/ititle-sheet0.png",
		"images/ititulo-sheet0.png",
		"images/bgrimoire-sheet0.png",
		"images/bcreditos-sheet0.png",
		"images/bhardreset-sheet0.png",
		"images/ipearltop-sheet0.png",
		"images/idropzone-sheet0.png",
		"images/safearea-sheet0.png",
		"images/stop1-sheet0.png",
		"images/bhome-sheet0.png",
		"images/breturn-sheet0.png",
		"images/dead-sheet0.png",
		"images/sboxspeech-sheet0.png",
		"images/sboxspeech2-sheet0.png",
		"images/sfdeathspeech.png",
		"images/igrimoire-sheet0.png",
		"images/imultiplier2-sheet0.png",
		"images/islidebar-sheet0.png",
		"images/iitemminiature-sheet0.png",
		"images/ifever-sheet0.png",
		"images/ifeverbar.png",
		"images/ifeverbar_top-sheet0.png",
		"images/ifeverbonus-sheet0.png",
		"images/ipearl-sheet0.png",
		"images/sfeverbar-sheet0.png",
		"images/sfeverbarunder-sheet0.png",
		"images/stutintrocarpet-sheet0.png",
		"images/stutintrocarpet-sheet1.png",
		"images/stutintrohand-sheet0.png",
		"images/stutintrogrimoire-sheet0.png",
		"images/sunlockgrimoire-sheet0.png",
		"images/ihandcursor-sheet0.png",
		"images/iboxbot-sheet0.png",
		"images/iboxmid-sheet0.png",
		"images/iboxtop-sheet0.png",
		"images/iending-sheet0.png",
		"images/iitem-sheet0.png",
		"images/imonsterpicture-sheet0.png",
		"images/imonsterpicture-sheet1.png",
		"images/iroombg-sheet0.png",
		"images/iscroll-sheet0.png",
		"images/iscroll-sheet1.png",
		"images/iscroll-sheet2.png",
		"images/ishowmonster-sheet0.png",
		"images/ishowmonster-sheet1.png",
		"images/iunlockmonster-sheet0.png",
		"images/sfmonsterdescription.png",
		"images/sfmonstername.png",
		"images/sitem-sheet0.png",
		"images/sitem-sheet1.png",
		"images/sitem-sheet2.png",
		"images/iexpbar-sheet0.png",
		"images/sunlockitem-sheet0.png",
		"images/ismoke-sheet0.png",
		"images/ismoke-sheet1.png",
		"images/iframegrimoire-sheet0.png",
		"images/btalentsshop-sheet0.png",
		"images/bitemsshop-sheet0.png",
		"images/icredits-sheet0.png",
		"images/itveffect.png",
		"images/itvbg.png",
		"media/fxbutton.m4a",
		"media/fxbutton.ogg",
		"media/fxexpbar.ogg",
		"media/fxexpbar.m4a",
		"media/fxflippage.m4a",
		"media/fxflippage.ogg",
		"media/fxitembreak - other.m4a",
		"media/fxitembreak - other.ogg",
		"media/fxitembreak - pot.m4a",
		"media/fxitembreak - pot.ogg",
		"media/fxopening.m4a",
		"media/fxopening.ogg",
		"media/fxspeechbig.m4a",
		"media/fxspeechbig.ogg",
		"media/fxspeechsmall.m4a",
		"media/fxspeechsmall.ogg",
		"media/fxopengrimoire.m4a",
		"media/fxopengrimoire.ogg",
		"media/fxmusic - credits - tremloadingloopl.m4a",
		"media/fxmusic - credits - tremloadingloopl.ogg",
		"media/fxmusic - game - going deep.ogg",
		"media/fxmusic - tutorial - rising.ogg",
		"media/fxmusic - menu and ending - little people at work.m4a",
		"media/fxmusic - menu and ending - little people at work.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"monsterlist.json",
		"grimoire.en.xml",
		"g.config.xml",
		"itemlist.json"
	]
}